# Generated by Django 2.1.1 on 2019-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_extended_access',
            new_name='is_paid_access',
        ),
        migrations.AddField(
            model_name='article',
            name='is_paid_access',
            field=models.BooleanField(default=False, verbose_name='Платный доступ'),
        ),
    ]
